### ISSUE TITLE
Smelting smite crashes the game

### ISSUE THREAD

**Issue by parcel31u** [diesieben07/Modjam-4#10]
http://pastebin.com/Da9RWaBJ

**Comment by diesieben07** [comment]
Cannot reproduce: http://i.imgur.com/J1VMVIY.gifv

**Comment by parcel31u** [comment]
http://i.imgur.com/mAHkoqC.png

**Comment by diesieben07** [comment]
Please provide a minimal test case. I am not going in and downloading all those mods.

**Comment by diesieben07** [comment]
Just for you I tried it with NEI installed. Works fine: http://i.imgur.com/01Y8KCW.png

**Comment by RCXcrafter** [comment]
I did some testing and I was able to reproduce it. I remembered having a similar issue when adding bad ores to an existing world, so I tried adding bad ores to an existing world, but smeling bad ores didn't cause crashes.
I then tried to do the same thing with a whole bunch of other mods installed too, and that got me this crash: http://pastebin.com/vVUTk0bj
I think this problem occurs because your ingot items have really random metadata values, that even differ between worlds. I think you can fix this by making the metadata values fixed like the ones for the blocks.

**Comment by diesieben07** [comment]
The metadata values are not random. If they are this is a problem, what makes you think they are random?

**Comment by RCXcrafter** [comment]
I'm not saying they are random but there seems no logic in them, especially since they're different for each world created. The block metadata values however, are very logical. I don't quite get why you did this for the items.

**Comment by diesieben07** [comment]
They are not random, they contain the BlockID of the associated ore. I can make it work without that, but if something is transferring items from one world to another it is not my fault.

**Comment by RCXcrafter** [comment]
Ah okay, that's quite clever. That also explains why the values are different for each world.
I don't have any mods that do things with block IDs as far as I know. I'll try some more testing with less mods.
