### ISSUE TITLE
Large world gen causes GC lag spikes.

### ISSUE THREAD

**Issue by NolanSyKinsley** [diesieben07/Modjam-4#11]
Sorry for wall of text, please bear with me.

This is part of a small modpack and I have reported it to them as well here: http://minecraft.curseforge.com/projects/dude-wheres-my-blocks/issues/1502 
I am reporting it here as well as I am 99% sure it is not the fault of the modpack.

Essentially I used admin command toolbox to pregen the chunks out to 10k blocks, but I ran into major issues when trying to do this and at ~40% completion it just kept locking up, so I decided to try and play as it was. 

I found it impossible to play due to 2.5 seconds of 0 fps every 10-15 seconds. This was being caused by the memory usage shooting up and the garbage collection sweeps hitting. The starting memory usage of the save was also over double what a freshly created save was using, the only difference being the world gen.

I then went and used jcmd to gather GC heap dumps of both a newly created world and the world where I genned the chunks. I used jvisualvm and traced the excess memory usage to badores, it seems that once a chunk is generated the location and type of every badore is held in memory in a weakhashmap due to something not releasing a reference to them, so MC keeps trying to load 3.2 million hashmap nodes and the garbage collection keeps dumping them when the memory fills causing a huge lag spike.

If needed I can provide the dumps.

**Comment by diesieben07** [comment]
Thanks for the report, I'll look into it. If you can provide the dumps that would be helpful.

**Comment by NolanSyKinsley** [comment]
Here ya yo https://www.dropbox.com/s/sp3g4kotq59kr6v/heaps.tar.gz?dl=0

**Comment by diesieben07** [comment]
This is weird. As far as I can see there is no WeakHashMap involved at all.
Since some BadOre ores have tile entities generating a lot of chunks will cause a lot of them to generate as well. 
I can try to find a way to do this without a TE but I am not sure it's possible due to the requirements of some of the ores.

However I did find something: MonitoredTileList$BlockData seems to be holding on to a lot of TileEntity instances. This tracks down to KCauldron. The source is [here](https://gitlab.prok.pw/KCauldron/KCauldron-MobiusCore/blob/fe6c62728309472c7e17f29e7941cfb5cce28131/src/main/java/mcp/mobius/mobiuscore/monitors/MonitoredTileList.java) (which seems to be down at the moment, but the [google cache](http://webcache.googleusercontent.com/search?q=cache%3Ahttps%3A%2F%2Fgitlab.prok.pw%2FKCauldron%2FKCauldron-MobiusCore%2Fblob%2Ffe6c62728309472c7e17f29e7941cfb5cce28131%2Fsrc%2Fmain%2Fjava%2Fmcp%2Fmobius%2Fmobiuscore%2Fmonitors%2FMonitoredTileList.java&oq=cache%3Ahttps%3A%2F%2Fgitlab.prok.pw%2FKCauldron%2FKCauldron-MobiusCore%2Fblob%2Ffe6c62728309472c7e17f29e7941cfb5cce28131%2Fsrc%2Fmain%2Fjava%2Fmcp%2Fmobius%2Fmobiuscore%2Fmonitors%2FMonitoredTileList.java) has it). This has the comment: 
> //TODO THIS IS WHERE THE CHUNK KEEP GETTING LOADED."

which is *really* suspicious to me.

**Comment by NolanSyKinsley** [comment]
I'm.. not using KCauldron, it is not in the mod list or one of the core mods that I know of, and this is a single player instance I am running on and it is running forge.

**Comment by diesieben07** [comment]
No idea what Mobius Core does. But could you try to reproduce it without that? And if you can, get me a heap dump without it?

**Comment by NolanSyKinsley** [comment]
MobiusCore is used by WAILA and Opis, I don't have opis installed but I do have WAILA. I will try and reproduce with only badores installed overnight tonight(takes a while to gen that many chunks). I have a feeling I will not be able to reproduce it.

**Comment by NolanSyKinsley** [comment]
Well, I removed mobius core and tried again with the same chunks, still happening. I think before I provide more heaps I will repeatedly bifurcate the pack and test to find out the true culprit.

**Comment by NolanSyKinsley** [comment]
Ahh, think I nailed it down... NEI absorbed WAILA and probably the relevant code from MobiusCore. I am getting ahold of chickenbones now. I will close this issue as it is not really a problem with your mod, but with an outside mod.
